name: pub_dev_app
description: Pub.dev api client.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.0.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # presentation
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  cached_network_image: ^3.0.0-nullsafety

  # application
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.3

  # infrastructure
  logger: ^1.0.0-nullsafety.0
  dio: ^4.0.0-beta5
  data_connection_checker: ^0.3.4
  hydrated_bloc: ^7.0.0-nullsafety.2
  pub_semver: ^2.0.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.3

  # utils
  meta: ^1.2.4
  supercharged: ^2.0.0
  get_it: ^6.0.0
  freezed_annotation: ^0.14.0
  json_annotation: ^4.0.0
  dartz: ^0.10.0-nullsafety.1
  built_collection: ^5.0.0
  selector: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  test: ^1.15.4

  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  freezed: ^0.14.0
  intl_utils: ^2.0.0

#dependency_overrides:
#  flutter_cache_manager: ^3.0.0-nullsafety  # Remove when sentry_flutter updates to null-safety.
#  http: ^0.13.0  # Remove when sentry_flutter updates to null-safety.
#  uuid: ^3.0.1  # Remove when sentry_flutter updates to null-safety.
#  dio: ^4.0.0-beta5  # Remove when pretty_dio_logger updates to null-safety.

flutter:
  # Includes the Material Icons font.
  uses-material-design: true
  assets:
    - config/

flutter_intl:
  enabled: false
  class_name: S
  main_locale: en
  arb_dir: lib/config/localization/arb
  output_dir: lib/config/localization/generated
  use_deferred_loading: false
